### ISSUE TITLE
vpolshchi.pl

### ISSUE THREAD

**Issue by krystian3w** [easylist/ruadlist#44]
New page, have nasty/ugly ads and anti-adblock (both can be recovered by webmaster in 48 hours).

```yaml
DOMAIN NAME:           vpolshchi.pl
registrant type:       organization
nameservers:           ns1.wp.pl. [212.77.106.200]
                       ns2.wp.pl. [153.19.88.162]
created:               2022.02.26 14:36:05
last modified:         2022.02.26 14:36:50
renewal date:          2023.02.26 14:36:05
```
